module vulkan.api.vma_3_4_0;

private:

import vulkan.api.vulkan_api;

public:

// Vulkan Memory Allocator 3.4.0 Include file converted to D (This is a generated file)
// 
// Generated by CTools (https://github.com/pvmoore/dlang-CTools)
// 
// Usage:
//   ** Start program
//   VMALoader.load();
//   ** 
//   VMALoader.unload();
//   ** Exit program

// VMALoader
private struct _VMALoader {
	import core.sys.windows.windows;
	import common.utils : throwIf;
	HANDLE handle;
	bool load() {
		debug {
			this.handle = LoadLibraryA("vma-3.4.0-debug.dll");
		} else {
			this.handle = LoadLibraryA("vma-3.4.0.dll");
		}
		if(!handle) return false;
		
		*(cast(void**)&vmaAllocateMemory) = GetProcAddress(handle, "vmaAllocateMemory"); throwIf(!vmaAllocateMemory);
		*(cast(void**)&vmaAllocateMemoryForBuffer) = GetProcAddress(handle, "vmaAllocateMemoryForBuffer"); throwIf(!vmaAllocateMemoryForBuffer);
		*(cast(void**)&vmaAllocateMemoryForImage) = GetProcAddress(handle, "vmaAllocateMemoryForImage"); throwIf(!vmaAllocateMemoryForImage);
		*(cast(void**)&vmaAllocateMemoryPages) = GetProcAddress(handle, "vmaAllocateMemoryPages"); throwIf(!vmaAllocateMemoryPages);
		*(cast(void**)&vmaBeginDefragmentation) = GetProcAddress(handle, "vmaBeginDefragmentation"); throwIf(!vmaBeginDefragmentation);
		*(cast(void**)&vmaBeginDefragmentationPass) = GetProcAddress(handle, "vmaBeginDefragmentationPass"); throwIf(!vmaBeginDefragmentationPass);
		*(cast(void**)&vmaBindBufferMemory) = GetProcAddress(handle, "vmaBindBufferMemory"); throwIf(!vmaBindBufferMemory);
		*(cast(void**)&vmaBindBufferMemory2) = GetProcAddress(handle, "vmaBindBufferMemory2"); throwIf(!vmaBindBufferMemory2);
		*(cast(void**)&vmaBindImageMemory) = GetProcAddress(handle, "vmaBindImageMemory"); throwIf(!vmaBindImageMemory);
		*(cast(void**)&vmaBindImageMemory2) = GetProcAddress(handle, "vmaBindImageMemory2"); throwIf(!vmaBindImageMemory2);
		*(cast(void**)&vmaBuildStatsString) = GetProcAddress(handle, "vmaBuildStatsString"); throwIf(!vmaBuildStatsString);
		*(cast(void**)&vmaBuildVirtualBlockStatsString) = GetProcAddress(handle, "vmaBuildVirtualBlockStatsString"); throwIf(!vmaBuildVirtualBlockStatsString);
		*(cast(void**)&vmaCalculatePoolStatistics) = GetProcAddress(handle, "vmaCalculatePoolStatistics"); throwIf(!vmaCalculatePoolStatistics);
		*(cast(void**)&vmaCalculateStatistics) = GetProcAddress(handle, "vmaCalculateStatistics"); throwIf(!vmaCalculateStatistics);
		*(cast(void**)&vmaCalculateVirtualBlockStatistics) = GetProcAddress(handle, "vmaCalculateVirtualBlockStatistics"); throwIf(!vmaCalculateVirtualBlockStatistics);
		*(cast(void**)&vmaCheckCorruption) = GetProcAddress(handle, "vmaCheckCorruption"); throwIf(!vmaCheckCorruption);
		*(cast(void**)&vmaCheckPoolCorruption) = GetProcAddress(handle, "vmaCheckPoolCorruption"); throwIf(!vmaCheckPoolCorruption);
		*(cast(void**)&vmaClearVirtualBlock) = GetProcAddress(handle, "vmaClearVirtualBlock"); throwIf(!vmaClearVirtualBlock);
		*(cast(void**)&vmaCopyAllocationToMemory) = GetProcAddress(handle, "vmaCopyAllocationToMemory"); throwIf(!vmaCopyAllocationToMemory);
		*(cast(void**)&vmaCopyMemoryToAllocation) = GetProcAddress(handle, "vmaCopyMemoryToAllocation"); throwIf(!vmaCopyMemoryToAllocation);
		*(cast(void**)&vmaCreateAliasingBuffer) = GetProcAddress(handle, "vmaCreateAliasingBuffer"); throwIf(!vmaCreateAliasingBuffer);
		*(cast(void**)&vmaCreateAliasingBuffer2) = GetProcAddress(handle, "vmaCreateAliasingBuffer2"); throwIf(!vmaCreateAliasingBuffer2);
		*(cast(void**)&vmaCreateAliasingImage) = GetProcAddress(handle, "vmaCreateAliasingImage"); throwIf(!vmaCreateAliasingImage);
		*(cast(void**)&vmaCreateAliasingImage2) = GetProcAddress(handle, "vmaCreateAliasingImage2"); throwIf(!vmaCreateAliasingImage2);
		*(cast(void**)&vmaCreateAllocator) = GetProcAddress(handle, "vmaCreateAllocator"); throwIf(!vmaCreateAllocator);
		*(cast(void**)&vmaCreateBuffer) = GetProcAddress(handle, "vmaCreateBuffer"); throwIf(!vmaCreateBuffer);
		*(cast(void**)&vmaCreateBufferWithAlignment) = GetProcAddress(handle, "vmaCreateBufferWithAlignment"); throwIf(!vmaCreateBufferWithAlignment);
		*(cast(void**)&vmaCreateImage) = GetProcAddress(handle, "vmaCreateImage"); throwIf(!vmaCreateImage);
		*(cast(void**)&vmaCreatePool) = GetProcAddress(handle, "vmaCreatePool"); throwIf(!vmaCreatePool);
		*(cast(void**)&vmaCreateVirtualBlock) = GetProcAddress(handle, "vmaCreateVirtualBlock"); throwIf(!vmaCreateVirtualBlock);
		*(cast(void**)&vmaDestroyAllocator) = GetProcAddress(handle, "vmaDestroyAllocator"); throwIf(!vmaDestroyAllocator);
		*(cast(void**)&vmaDestroyBuffer) = GetProcAddress(handle, "vmaDestroyBuffer"); throwIf(!vmaDestroyBuffer);
		*(cast(void**)&vmaDestroyImage) = GetProcAddress(handle, "vmaDestroyImage"); throwIf(!vmaDestroyImage);
		*(cast(void**)&vmaDestroyPool) = GetProcAddress(handle, "vmaDestroyPool"); throwIf(!vmaDestroyPool);
		*(cast(void**)&vmaDestroyVirtualBlock) = GetProcAddress(handle, "vmaDestroyVirtualBlock"); throwIf(!vmaDestroyVirtualBlock);
		*(cast(void**)&vmaEndDefragmentation) = GetProcAddress(handle, "vmaEndDefragmentation"); throwIf(!vmaEndDefragmentation);
		*(cast(void**)&vmaEndDefragmentationPass) = GetProcAddress(handle, "vmaEndDefragmentationPass"); throwIf(!vmaEndDefragmentationPass);
		*(cast(void**)&vmaFindMemoryTypeIndex) = GetProcAddress(handle, "vmaFindMemoryTypeIndex"); throwIf(!vmaFindMemoryTypeIndex);
		*(cast(void**)&vmaFindMemoryTypeIndexForBufferInfo) = GetProcAddress(handle, "vmaFindMemoryTypeIndexForBufferInfo"); throwIf(!vmaFindMemoryTypeIndexForBufferInfo);
		*(cast(void**)&vmaFindMemoryTypeIndexForImageInfo) = GetProcAddress(handle, "vmaFindMemoryTypeIndexForImageInfo"); throwIf(!vmaFindMemoryTypeIndexForImageInfo);
		*(cast(void**)&vmaFlushAllocation) = GetProcAddress(handle, "vmaFlushAllocation"); throwIf(!vmaFlushAllocation);
		*(cast(void**)&vmaFlushAllocations) = GetProcAddress(handle, "vmaFlushAllocations"); throwIf(!vmaFlushAllocations);
		*(cast(void**)&vmaFreeMemory) = GetProcAddress(handle, "vmaFreeMemory"); throwIf(!vmaFreeMemory);
		*(cast(void**)&vmaFreeMemoryPages) = GetProcAddress(handle, "vmaFreeMemoryPages"); throwIf(!vmaFreeMemoryPages);
		*(cast(void**)&vmaFreeStatsString) = GetProcAddress(handle, "vmaFreeStatsString"); throwIf(!vmaFreeStatsString);
		*(cast(void**)&vmaFreeVirtualBlockStatsString) = GetProcAddress(handle, "vmaFreeVirtualBlockStatsString"); throwIf(!vmaFreeVirtualBlockStatsString);
		*(cast(void**)&vmaGetAllocationInfo) = GetProcAddress(handle, "vmaGetAllocationInfo"); throwIf(!vmaGetAllocationInfo);
		*(cast(void**)&vmaGetAllocationInfo2) = GetProcAddress(handle, "vmaGetAllocationInfo2"); throwIf(!vmaGetAllocationInfo2);
		*(cast(void**)&vmaGetAllocationMemoryProperties) = GetProcAddress(handle, "vmaGetAllocationMemoryProperties"); throwIf(!vmaGetAllocationMemoryProperties);
		*(cast(void**)&vmaGetAllocatorInfo) = GetProcAddress(handle, "vmaGetAllocatorInfo"); throwIf(!vmaGetAllocatorInfo);
		*(cast(void**)&vmaGetHeapBudgets) = GetProcAddress(handle, "vmaGetHeapBudgets"); throwIf(!vmaGetHeapBudgets);
		*(cast(void**)&vmaGetMemoryProperties) = GetProcAddress(handle, "vmaGetMemoryProperties"); throwIf(!vmaGetMemoryProperties);
		*(cast(void**)&vmaGetMemoryTypeProperties) = GetProcAddress(handle, "vmaGetMemoryTypeProperties"); throwIf(!vmaGetMemoryTypeProperties);
		*(cast(void**)&vmaGetMemoryWin32Handle) = GetProcAddress(handle, "vmaGetMemoryWin32Handle"); throwIf(!vmaGetMemoryWin32Handle);
		*(cast(void**)&vmaGetPhysicalDeviceProperties) = GetProcAddress(handle, "vmaGetPhysicalDeviceProperties"); throwIf(!vmaGetPhysicalDeviceProperties);
		*(cast(void**)&vmaGetPoolName) = GetProcAddress(handle, "vmaGetPoolName"); throwIf(!vmaGetPoolName);
		*(cast(void**)&vmaGetPoolStatistics) = GetProcAddress(handle, "vmaGetPoolStatistics"); throwIf(!vmaGetPoolStatistics);
		*(cast(void**)&vmaGetVirtualAllocationInfo) = GetProcAddress(handle, "vmaGetVirtualAllocationInfo"); throwIf(!vmaGetVirtualAllocationInfo);
		*(cast(void**)&vmaGetVirtualBlockStatistics) = GetProcAddress(handle, "vmaGetVirtualBlockStatistics"); throwIf(!vmaGetVirtualBlockStatistics);
		*(cast(void**)&vmaInvalidateAllocation) = GetProcAddress(handle, "vmaInvalidateAllocation"); throwIf(!vmaInvalidateAllocation);
		*(cast(void**)&vmaInvalidateAllocations) = GetProcAddress(handle, "vmaInvalidateAllocations"); throwIf(!vmaInvalidateAllocations);
		*(cast(void**)&vmaIsVirtualBlockEmpty) = GetProcAddress(handle, "vmaIsVirtualBlockEmpty"); throwIf(!vmaIsVirtualBlockEmpty);
		*(cast(void**)&vmaMapMemory) = GetProcAddress(handle, "vmaMapMemory"); throwIf(!vmaMapMemory);
		*(cast(void**)&vmaSetAllocationName) = GetProcAddress(handle, "vmaSetAllocationName"); throwIf(!vmaSetAllocationName);
		*(cast(void**)&vmaSetAllocationUserData) = GetProcAddress(handle, "vmaSetAllocationUserData"); throwIf(!vmaSetAllocationUserData);
		*(cast(void**)&vmaSetCurrentFrameIndex) = GetProcAddress(handle, "vmaSetCurrentFrameIndex"); throwIf(!vmaSetCurrentFrameIndex);
		*(cast(void**)&vmaSetPoolName) = GetProcAddress(handle, "vmaSetPoolName"); throwIf(!vmaSetPoolName);
		*(cast(void**)&vmaSetVirtualAllocationUserData) = GetProcAddress(handle, "vmaSetVirtualAllocationUserData"); throwIf(!vmaSetVirtualAllocationUserData);
		*(cast(void**)&vmaUnmapMemory) = GetProcAddress(handle, "vmaUnmapMemory"); throwIf(!vmaUnmapMemory);
		*(cast(void**)&vmaVirtualAllocate) = GetProcAddress(handle, "vmaVirtualAllocate"); throwIf(!vmaVirtualAllocate);
		*(cast(void**)&vmaVirtualFree) = GetProcAddress(handle, "vmaVirtualFree"); throwIf(!vmaVirtualFree);
		return true;
	}
	void unload() {
		if(handle) FreeLibrary(handle);
	}
}
__gshared _VMALoader VMALoader;
// End of VMALoader

// Aliases
alias BOOL = int;
alias BYTE = ubyte;
alias CCHAR = char;
alias CHAR = char;
alias DWORD = uint;
alias DWORD64 = ulong;
alias FLOAT = float;
alias FXPT2DOT30 = int;
alias HANDLE = void*;
alias HANDLE64 = void*;
alias HFILE = int;
alias HGDIOBJ = void*;
alias HPCON = void*;
alias HRESULT = int;
alias INT = int;
alias INT16 = short;
alias INT32 = int;
alias INT64 = long;
alias INT8 = char;
alias INT_PTR = long;
alias LONG = int;
alias LONG64 = long;
alias LONGLONG = long;
alias LONG_PTR = long;
alias LPCVOID = void*;
alias LPINT = int*;
alias LPLONG = int*;
alias LPVOID = void*;
alias MENUTEMPLATEA = void;
alias MENUTEMPLATEW = void;
alias PUINT = uint*;
alias PUMS_COMPLETION_LIST = void*;
alias PUMS_CONTEXT = void*;
alias PVOID = void*;
alias PVOID64 = void*;
alias SHORT = short;
alias UCHAR = ubyte;
alias UCSCHAR = uint;
alias UINT = uint;
alias UINT16 = ushort;
alias UINT32 = uint;
alias UINT64 = ulong;
alias UINT8 = ubyte;
alias UINT_PTR = ulong;
alias ULONG = uint;
alias ULONG64 = ulong;
alias ULONGLONG = ulong;
alias ULONG_PTR = ulong;
alias USHORT = ushort;
alias VmaAllocation = VmaAllocation_T*;
alias VmaAllocationCreateFlags = VkFlags;
alias VmaAllocator = VmaAllocator_T*;
alias VmaAllocatorCreateFlags = VkFlags;
alias VmaDefragmentationContext = VmaDefragmentationContext_T*;
alias VmaDefragmentationFlags = VkFlags;
alias VmaPool = VmaPool_T*;
alias VmaPoolCreateFlags = VkFlags;
alias VmaVirtualAllocation = VmaVirtualAllocation_T*;
alias VmaVirtualAllocationCreateFlags = VkFlags;
alias VmaVirtualBlock = VmaVirtualBlock_T*;
alias VmaVirtualBlockCreateFlags = VkFlags;
alias WORD = ushort;
alias __time64_t = long;
alias errno_t = int;
alias int16_t = short;
alias int32_t = int;
alias int64_t = long;
alias int8_t = char;
alias size_t = ulong;
alias uint16_t = ushort;
alias uint32_t = uint;
alias uint64_t = ulong;
alias uint8_t = ubyte;
alias uintptr_t = ulong;
alias va_list = immutable(char)*;
alias wchar_t = ushort;
alias wctype_t = ushort;
alias wint_t = ushort;
alias PFN_vmaAllocateDeviceMemoryFunction = extern(Windows) void function(VmaAllocator allocator, uint32_t memoryType, VkDeviceMemory memory, VkDeviceSize size, void* pUserData) nothrow;
alias PFN_vmaCheckDefragmentationBreakFunction = extern(Windows) VkBool32 function(void* pUserData) nothrow;
alias PFN_vmaFreeDeviceMemoryFunction = extern(Windows) void function(VmaAllocator allocator, uint32_t memoryType, VkDeviceMemory memory, VkDeviceSize size, void* pUserData) nothrow;

// Enums
enum VmaAllocationCreateFlagBits {
	VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT = 0x00000001,
	VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT = 0x00000002,
	VMA_ALLOCATION_CREATE_MAPPED_BIT = 0x00000004,
	VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT = 0x00000020,
	VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT = 0x00000040,
	VMA_ALLOCATION_CREATE_DONT_BIND_BIT = 0x00000080,
	VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT = 0x00000100,
	VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT = 0x00000200,
	VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT = 0x00000400,
	VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT = 0x00000800,
	VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT = 0x00001000,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT = 0x00010000,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT = 0x00020000,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT = 0x00040000,
	VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_MASK = VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT | VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT | VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT,
	VMA_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaAllocationCreateFlagBits {
	VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT,
	VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT,
	VMA_ALLOCATION_CREATE_MAPPED_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_MAPPED_BIT,
	VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT,
	VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT,
	VMA_ALLOCATION_CREATE_DONT_BIND_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_DONT_BIND_BIT,
	VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT,
	VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT,
	VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT,
	VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT,
	VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT,
	VMA_ALLOCATION_CREATE_STRATEGY_MASK = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_STRATEGY_MASK,
	VMA_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM = VmaAllocationCreateFlagBits.VMA_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM,
}
enum VmaAllocatorCreateFlagBits {
	VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT = 0x00000001,
	VMA_ALLOCATOR_CREATE_KHR_DEDICATED_ALLOCATION_BIT = 0x00000002,
	VMA_ALLOCATOR_CREATE_KHR_BIND_MEMORY2_BIT = 0x00000004,
	VMA_ALLOCATOR_CREATE_EXT_MEMORY_BUDGET_BIT = 0x00000008,
	VMA_ALLOCATOR_CREATE_AMD_DEVICE_COHERENT_MEMORY_BIT = 0x00000010,
	VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT = 0x00000020,
	VMA_ALLOCATOR_CREATE_EXT_MEMORY_PRIORITY_BIT = 0x00000040,
	VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE4_BIT = 0x00000080,
	VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE5_BIT = 0x00000100,
	VMA_ALLOCATOR_CREATE_KHR_EXTERNAL_MEMORY_WIN32_BIT = 0x00000200,
	VMA_ALLOCATOR_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaAllocatorCreateFlagBits {
	VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT,
	VMA_ALLOCATOR_CREATE_KHR_DEDICATED_ALLOCATION_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_KHR_DEDICATED_ALLOCATION_BIT,
	VMA_ALLOCATOR_CREATE_KHR_BIND_MEMORY2_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_KHR_BIND_MEMORY2_BIT,
	VMA_ALLOCATOR_CREATE_EXT_MEMORY_BUDGET_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_EXT_MEMORY_BUDGET_BIT,
	VMA_ALLOCATOR_CREATE_AMD_DEVICE_COHERENT_MEMORY_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_AMD_DEVICE_COHERENT_MEMORY_BIT,
	VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT,
	VMA_ALLOCATOR_CREATE_EXT_MEMORY_PRIORITY_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_EXT_MEMORY_PRIORITY_BIT,
	VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE4_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE4_BIT,
	VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE5_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_KHR_MAINTENANCE5_BIT,
	VMA_ALLOCATOR_CREATE_KHR_EXTERNAL_MEMORY_WIN32_BIT = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_KHR_EXTERNAL_MEMORY_WIN32_BIT,
	VMA_ALLOCATOR_CREATE_FLAG_BITS_MAX_ENUM = VmaAllocatorCreateFlagBits.VMA_ALLOCATOR_CREATE_FLAG_BITS_MAX_ENUM,
}
enum VmaDefragmentationFlagBits {
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT = 0x1,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT = 0x2,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT = 0x4,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT = 0x8,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_MASK = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT | VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT | VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT | VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT,
	VMA_DEFRAGMENTATION_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaDefragmentationFlagBits {
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT = VmaDefragmentationFlagBits.VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT = VmaDefragmentationFlagBits.VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT = VmaDefragmentationFlagBits.VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT = VmaDefragmentationFlagBits.VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT,
	VMA_DEFRAGMENTATION_FLAG_ALGORITHM_MASK = VmaDefragmentationFlagBits.VMA_DEFRAGMENTATION_FLAG_ALGORITHM_MASK,
	VMA_DEFRAGMENTATION_FLAG_BITS_MAX_ENUM = VmaDefragmentationFlagBits.VMA_DEFRAGMENTATION_FLAG_BITS_MAX_ENUM,
}
enum VmaDefragmentationMoveOperation {
	VMA_DEFRAGMENTATION_MOVE_OPERATION_COPY = 0,
	VMA_DEFRAGMENTATION_MOVE_OPERATION_IGNORE = 1,
	VMA_DEFRAGMENTATION_MOVE_OPERATION_DESTROY = 2,
}
enum : VmaDefragmentationMoveOperation {
	VMA_DEFRAGMENTATION_MOVE_OPERATION_COPY = VmaDefragmentationMoveOperation.VMA_DEFRAGMENTATION_MOVE_OPERATION_COPY,
	VMA_DEFRAGMENTATION_MOVE_OPERATION_IGNORE = VmaDefragmentationMoveOperation.VMA_DEFRAGMENTATION_MOVE_OPERATION_IGNORE,
	VMA_DEFRAGMENTATION_MOVE_OPERATION_DESTROY = VmaDefragmentationMoveOperation.VMA_DEFRAGMENTATION_MOVE_OPERATION_DESTROY,
}
enum VmaMemoryUsage {
	VMA_MEMORY_USAGE_UNKNOWN = 0,
	VMA_MEMORY_USAGE_GPU_ONLY = 1,
	VMA_MEMORY_USAGE_CPU_ONLY = 2,
	VMA_MEMORY_USAGE_CPU_TO_GPU = 3,
	VMA_MEMORY_USAGE_GPU_TO_CPU = 4,
	VMA_MEMORY_USAGE_CPU_COPY = 5,
	VMA_MEMORY_USAGE_GPU_LAZILY_ALLOCATED = 6,
	VMA_MEMORY_USAGE_AUTO = 7,
	VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE = 8,
	VMA_MEMORY_USAGE_AUTO_PREFER_HOST = 9,
	VMA_MEMORY_USAGE_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaMemoryUsage {
	VMA_MEMORY_USAGE_UNKNOWN = VmaMemoryUsage.VMA_MEMORY_USAGE_UNKNOWN,
	VMA_MEMORY_USAGE_GPU_ONLY = VmaMemoryUsage.VMA_MEMORY_USAGE_GPU_ONLY,
	VMA_MEMORY_USAGE_CPU_ONLY = VmaMemoryUsage.VMA_MEMORY_USAGE_CPU_ONLY,
	VMA_MEMORY_USAGE_CPU_TO_GPU = VmaMemoryUsage.VMA_MEMORY_USAGE_CPU_TO_GPU,
	VMA_MEMORY_USAGE_GPU_TO_CPU = VmaMemoryUsage.VMA_MEMORY_USAGE_GPU_TO_CPU,
	VMA_MEMORY_USAGE_CPU_COPY = VmaMemoryUsage.VMA_MEMORY_USAGE_CPU_COPY,
	VMA_MEMORY_USAGE_GPU_LAZILY_ALLOCATED = VmaMemoryUsage.VMA_MEMORY_USAGE_GPU_LAZILY_ALLOCATED,
	VMA_MEMORY_USAGE_AUTO = VmaMemoryUsage.VMA_MEMORY_USAGE_AUTO,
	VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE = VmaMemoryUsage.VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE,
	VMA_MEMORY_USAGE_AUTO_PREFER_HOST = VmaMemoryUsage.VMA_MEMORY_USAGE_AUTO_PREFER_HOST,
	VMA_MEMORY_USAGE_MAX_ENUM = VmaMemoryUsage.VMA_MEMORY_USAGE_MAX_ENUM,
}
enum VmaPoolCreateFlagBits {
	VMA_POOL_CREATE_IGNORE_BUFFER_IMAGE_GRANULARITY_BIT = 0x00000002,
	VMA_POOL_CREATE_LINEAR_ALGORITHM_BIT = 0x00000004,
	VMA_POOL_CREATE_ALGORITHM_MASK = VMA_POOL_CREATE_LINEAR_ALGORITHM_BIT,
	VMA_POOL_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaPoolCreateFlagBits {
	VMA_POOL_CREATE_IGNORE_BUFFER_IMAGE_GRANULARITY_BIT = VmaPoolCreateFlagBits.VMA_POOL_CREATE_IGNORE_BUFFER_IMAGE_GRANULARITY_BIT,
	VMA_POOL_CREATE_LINEAR_ALGORITHM_BIT = VmaPoolCreateFlagBits.VMA_POOL_CREATE_LINEAR_ALGORITHM_BIT,
	VMA_POOL_CREATE_ALGORITHM_MASK = VmaPoolCreateFlagBits.VMA_POOL_CREATE_ALGORITHM_MASK,
	VMA_POOL_CREATE_FLAG_BITS_MAX_ENUM = VmaPoolCreateFlagBits.VMA_POOL_CREATE_FLAG_BITS_MAX_ENUM,
}
enum VmaVirtualAllocationCreateFlagBits {
	VMA_VIRTUAL_ALLOCATION_CREATE_UPPER_ADDRESS_BIT = cast(int)VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MASK = VMA_ALLOCATION_CREATE_STRATEGY_MASK,
	VMA_VIRTUAL_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaVirtualAllocationCreateFlagBits {
	VMA_VIRTUAL_ALLOCATION_CREATE_UPPER_ADDRESS_BIT = VmaVirtualAllocationCreateFlagBits.VMA_VIRTUAL_ALLOCATION_CREATE_UPPER_ADDRESS_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT = VmaVirtualAllocationCreateFlagBits.VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT = VmaVirtualAllocationCreateFlagBits.VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT = VmaVirtualAllocationCreateFlagBits.VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT,
	VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MASK = VmaVirtualAllocationCreateFlagBits.VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MASK,
	VMA_VIRTUAL_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM = VmaVirtualAllocationCreateFlagBits.VMA_VIRTUAL_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM,
}
enum VmaVirtualBlockCreateFlagBits {
	VMA_VIRTUAL_BLOCK_CREATE_LINEAR_ALGORITHM_BIT = 0x00000001,
	VMA_VIRTUAL_BLOCK_CREATE_ALGORITHM_MASK = VMA_VIRTUAL_BLOCK_CREATE_LINEAR_ALGORITHM_BIT,
	VMA_VIRTUAL_BLOCK_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
}
enum : VmaVirtualBlockCreateFlagBits {
	VMA_VIRTUAL_BLOCK_CREATE_LINEAR_ALGORITHM_BIT = VmaVirtualBlockCreateFlagBits.VMA_VIRTUAL_BLOCK_CREATE_LINEAR_ALGORITHM_BIT,
	VMA_VIRTUAL_BLOCK_CREATE_ALGORITHM_MASK = VmaVirtualBlockCreateFlagBits.VMA_VIRTUAL_BLOCK_CREATE_ALGORITHM_MASK,
	VMA_VIRTUAL_BLOCK_CREATE_FLAG_BITS_MAX_ENUM = VmaVirtualBlockCreateFlagBits.VMA_VIRTUAL_BLOCK_CREATE_FLAG_BITS_MAX_ENUM,
}

// Unions

// Structs
struct VmaAllocationCreateInfo {
	VmaAllocationCreateFlags flags;
	VmaMemoryUsage usage;
	VkMemoryPropertyFlags requiredFlags;
	VkMemoryPropertyFlags preferredFlags;
	uint32_t memoryTypeBits;
	VmaPool pool;
	void* pUserData;
	float priority;
}
struct VmaAllocationInfo {
	uint32_t memoryType;
	VkDeviceMemory deviceMemory;
	VkDeviceSize offset;
	VkDeviceSize size;
	void* pMappedData;
	void* pUserData;
	immutable(char)* pName;
}
struct VmaAllocationInfo2 {
	VmaAllocationInfo allocationInfo;
	VkDeviceSize blockSize;
	VkBool32 dedicatedMemory;
}
struct VmaAllocation_T {
}
struct VmaAllocatorCreateInfo {
	VmaAllocatorCreateFlags flags;
	VkPhysicalDevice physicalDevice;
	VkDevice device;
	VkDeviceSize preferredLargeHeapBlockSize;
	VkAllocationCallbacks* pAllocationCallbacks;
	VmaDeviceMemoryCallbacks* pDeviceMemoryCallbacks;
	VkDeviceSize* pHeapSizeLimit;
	VmaVulkanFunctions* pVulkanFunctions;
	VkInstance instance;
	uint32_t vulkanApiVersion;
	VkExternalMemoryHandleTypeFlagsKHR* pTypeExternalMemoryHandleTypes;
}
struct VmaAllocatorInfo {
	VkInstance instance;
	VkPhysicalDevice physicalDevice;
	VkDevice device;
}
struct VmaAllocator_T {
}
struct VmaBudget {
	VmaStatistics statistics;
	VkDeviceSize usage;
	VkDeviceSize budget;
}
struct VmaDefragmentationContext_T {
}
struct VmaDefragmentationInfo {
	VmaDefragmentationFlags flags;
	VmaPool pool;
	VkDeviceSize maxBytesPerPass;
	uint32_t maxAllocationsPerPass;
	PFN_vmaCheckDefragmentationBreakFunction pfnBreakCallback;
	void* pBreakCallbackUserData;
}
struct VmaDefragmentationMove {
	VmaDefragmentationMoveOperation operation;
	VmaAllocation srcAllocation;
	VmaAllocation dstTmpAllocation;
}
struct VmaDefragmentationPassMoveInfo {
	uint32_t moveCount;
	VmaDefragmentationMove* pMoves;
}
struct VmaDefragmentationStats {
	VkDeviceSize bytesMoved;
	VkDeviceSize bytesFreed;
	uint32_t allocationsMoved;
	uint32_t deviceMemoryBlocksFreed;
}
struct VmaDetailedStatistics {
	VmaStatistics statistics;
	uint32_t unusedRangeCount;
	VkDeviceSize allocationSizeMin;
	VkDeviceSize allocationSizeMax;
	VkDeviceSize unusedRangeSizeMin;
	VkDeviceSize unusedRangeSizeMax;
}
struct VmaDeviceMemoryCallbacks {
	PFN_vmaAllocateDeviceMemoryFunction pfnAllocate;
	PFN_vmaFreeDeviceMemoryFunction pfnFree;
	void* pUserData;
}
struct VmaPoolCreateInfo {
	uint32_t memoryTypeIndex;
	VmaPoolCreateFlags flags;
	VkDeviceSize blockSize;
	size_t minBlockCount;
	size_t maxBlockCount;
	float priority;
	VkDeviceSize minAllocationAlignment;
	void* pMemoryAllocateNext;
}
struct VmaPool_T {
}
struct VmaStatistics {
	uint32_t blockCount;
	uint32_t allocationCount;
	VkDeviceSize blockBytes;
	VkDeviceSize allocationBytes;
}
struct VmaTotalStatistics {
	VmaDetailedStatistics[32U] memoryType;
	VmaDetailedStatistics[16U] memoryHeap;
	VmaDetailedStatistics total;
}
struct VmaVirtualAllocationCreateInfo {
	VkDeviceSize size;
	VkDeviceSize alignment;
	VmaVirtualAllocationCreateFlags flags;
	void* pUserData;
}
struct VmaVirtualAllocationInfo {
	VkDeviceSize offset;
	VkDeviceSize size;
	void* pUserData;
}
struct VmaVirtualAllocation_T {
}
struct VmaVirtualBlockCreateInfo {
	VkDeviceSize size;
	VmaVirtualBlockCreateFlags flags;
	VkAllocationCallbacks* pAllocationCallbacks;
}
struct VmaVirtualBlock_T {
}
struct VmaVulkanFunctions {
	PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
	PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;
	PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
	PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
	PFN_vkAllocateMemory vkAllocateMemory;
	PFN_vkFreeMemory vkFreeMemory;
	PFN_vkMapMemory vkMapMemory;
	PFN_vkUnmapMemory vkUnmapMemory;
	PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
	PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
	PFN_vkBindBufferMemory vkBindBufferMemory;
	PFN_vkBindImageMemory vkBindImageMemory;
	PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
	PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
	PFN_vkCreateBuffer vkCreateBuffer;
	PFN_vkDestroyBuffer vkDestroyBuffer;
	PFN_vkCreateImage vkCreateImage;
	PFN_vkDestroyImage vkDestroyImage;
	PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
	PFN_vkGetBufferMemoryRequirements2KHR vkGetBufferMemoryRequirements2KHR;
	PFN_vkGetImageMemoryRequirements2KHR vkGetImageMemoryRequirements2KHR;
	PFN_vkBindBufferMemory2KHR vkBindBufferMemory2KHR;
	PFN_vkBindImageMemory2KHR vkBindImageMemory2KHR;
	PFN_vkGetPhysicalDeviceMemoryProperties2KHR vkGetPhysicalDeviceMemoryProperties2KHR;
	PFN_vkGetDeviceBufferMemoryRequirementsKHR vkGetDeviceBufferMemoryRequirements;
	PFN_vkGetDeviceImageMemoryRequirementsKHR vkGetDeviceImageMemoryRequirements;
	PFN_vkGetMemoryWin32HandleKHR vkGetMemoryWin32HandleKHR;
}

// Global variables

extern(Windows) { nothrow __gshared {

}} // extern(Windows), __gshared

extern(C) { nothrow __gshared {

VkResult function(VmaAllocator allocator, VkMemoryRequirements* pVkMemoryRequirements, VmaAllocationCreateInfo* pCreateInfo, VmaAllocation* pAllocation, VmaAllocationInfo* pAllocationInfo)
	vmaAllocateMemory;

VkResult function(VmaAllocator allocator, VkBuffer buffer, VmaAllocationCreateInfo* pCreateInfo, VmaAllocation* pAllocation, VmaAllocationInfo* pAllocationInfo)
	vmaAllocateMemoryForBuffer;

VkResult function(VmaAllocator allocator, VkImage image, VmaAllocationCreateInfo* pCreateInfo, VmaAllocation* pAllocation, VmaAllocationInfo* pAllocationInfo)
	vmaAllocateMemoryForImage;

VkResult function(VmaAllocator allocator, VkMemoryRequirements* pVkMemoryRequirements, VmaAllocationCreateInfo* pCreateInfo, size_t allocationCount, VmaAllocation* pAllocations, VmaAllocationInfo* pAllocationInfo)
	vmaAllocateMemoryPages;

VkResult function(VmaAllocator allocator, VmaDefragmentationInfo* pInfo, VmaDefragmentationContext* pContext)
	vmaBeginDefragmentation;

VkResult function(VmaAllocator allocator, VmaDefragmentationContext context, VmaDefragmentationPassMoveInfo* pPassInfo)
	vmaBeginDefragmentationPass;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkBuffer buffer)
	vmaBindBufferMemory;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkDeviceSize allocationLocalOffset, VkBuffer buffer, void* pNext)
	vmaBindBufferMemory2;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkImage image)
	vmaBindImageMemory;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkDeviceSize allocationLocalOffset, VkImage image, void* pNext)
	vmaBindImageMemory2;

void function(VmaAllocator allocator, immutable(char)** ppStatsString, VkBool32 detailedMap)
	vmaBuildStatsString;

void function(VmaVirtualBlock virtualBlock, immutable(char)** ppStatsString, VkBool32 detailedMap)
	vmaBuildVirtualBlockStatsString;

void function(VmaAllocator allocator, VmaPool pool, VmaDetailedStatistics* pPoolStats)
	vmaCalculatePoolStatistics;

void function(VmaAllocator allocator, VmaTotalStatistics* pStats)
	vmaCalculateStatistics;

void function(VmaVirtualBlock virtualBlock, VmaDetailedStatistics* pStats)
	vmaCalculateVirtualBlockStatistics;

VkResult function(VmaAllocator allocator, uint32_t memoryTypeBits)
	vmaCheckCorruption;

VkResult function(VmaAllocator allocator, VmaPool pool)
	vmaCheckPoolCorruption;

void function(VmaVirtualBlock virtualBlock)
	vmaClearVirtualBlock;

VkResult function(VmaAllocator allocator, VmaAllocation srcAllocation, VkDeviceSize srcAllocationLocalOffset, void* pDstHostPointer, VkDeviceSize size)
	vmaCopyAllocationToMemory;

VkResult function(VmaAllocator allocator, void* pSrcHostPointer, VmaAllocation dstAllocation, VkDeviceSize dstAllocationLocalOffset, VkDeviceSize size)
	vmaCopyMemoryToAllocation;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkBufferCreateInfo* pBufferCreateInfo, VkBuffer* pBuffer)
	vmaCreateAliasingBuffer;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkDeviceSize allocationLocalOffset, VkBufferCreateInfo* pBufferCreateInfo, VkBuffer* pBuffer)
	vmaCreateAliasingBuffer2;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkImageCreateInfo* pImageCreateInfo, VkImage* pImage)
	vmaCreateAliasingImage;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkDeviceSize allocationLocalOffset, VkImageCreateInfo* pImageCreateInfo, VkImage* pImage)
	vmaCreateAliasingImage2;

VkResult function(VmaAllocatorCreateInfo* pCreateInfo, VmaAllocator* pAllocator)
	vmaCreateAllocator;

VkResult function(VmaAllocator allocator, VkBufferCreateInfo* pBufferCreateInfo, VmaAllocationCreateInfo* pAllocationCreateInfo, VkBuffer* pBuffer, VmaAllocation* pAllocation, VmaAllocationInfo* pAllocationInfo)
	vmaCreateBuffer;

VkResult function(VmaAllocator allocator, VkBufferCreateInfo* pBufferCreateInfo, VmaAllocationCreateInfo* pAllocationCreateInfo, VkDeviceSize minAlignment, VkBuffer* pBuffer, VmaAllocation* pAllocation, VmaAllocationInfo* pAllocationInfo)
	vmaCreateBufferWithAlignment;

VkResult function(VmaAllocator allocator, VkImageCreateInfo* pImageCreateInfo, VmaAllocationCreateInfo* pAllocationCreateInfo, VkImage* pImage, VmaAllocation* pAllocation, VmaAllocationInfo* pAllocationInfo)
	vmaCreateImage;

VkResult function(VmaAllocator allocator, VmaPoolCreateInfo* pCreateInfo, VmaPool* pPool)
	vmaCreatePool;

VkResult function(VmaVirtualBlockCreateInfo* pCreateInfo, VmaVirtualBlock* pVirtualBlock)
	vmaCreateVirtualBlock;

void function(VmaAllocator allocator)
	vmaDestroyAllocator;

void function(VmaAllocator allocator, VkBuffer buffer, VmaAllocation allocation)
	vmaDestroyBuffer;

void function(VmaAllocator allocator, VkImage image, VmaAllocation allocation)
	vmaDestroyImage;

void function(VmaAllocator allocator, VmaPool pool)
	vmaDestroyPool;

void function(VmaVirtualBlock virtualBlock)
	vmaDestroyVirtualBlock;

void function(VmaAllocator allocator, VmaDefragmentationContext context, VmaDefragmentationStats* pStats)
	vmaEndDefragmentation;

VkResult function(VmaAllocator allocator, VmaDefragmentationContext context, VmaDefragmentationPassMoveInfo* pPassInfo)
	vmaEndDefragmentationPass;

VkResult function(VmaAllocator allocator, uint32_t memoryTypeBits, VmaAllocationCreateInfo* pAllocationCreateInfo, uint32_t* pMemoryTypeIndex)
	vmaFindMemoryTypeIndex;

VkResult function(VmaAllocator allocator, VkBufferCreateInfo* pBufferCreateInfo, VmaAllocationCreateInfo* pAllocationCreateInfo, uint32_t* pMemoryTypeIndex)
	vmaFindMemoryTypeIndexForBufferInfo;

VkResult function(VmaAllocator allocator, VkImageCreateInfo* pImageCreateInfo, VmaAllocationCreateInfo* pAllocationCreateInfo, uint32_t* pMemoryTypeIndex)
	vmaFindMemoryTypeIndexForImageInfo;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkDeviceSize offset, VkDeviceSize size)
	vmaFlushAllocation;

VkResult function(VmaAllocator allocator, uint32_t allocationCount, VmaAllocation* allocations, VkDeviceSize* offsets, VkDeviceSize* sizes)
	vmaFlushAllocations;

void function(VmaAllocator allocator, VmaAllocation allocation)
	vmaFreeMemory;

void function(VmaAllocator allocator, size_t allocationCount, VmaAllocation* pAllocations)
	vmaFreeMemoryPages;

void function(VmaAllocator allocator, immutable(char)* pStatsString)
	vmaFreeStatsString;

void function(VmaVirtualBlock virtualBlock, immutable(char)* pStatsString)
	vmaFreeVirtualBlockStatsString;

void function(VmaAllocator allocator, VmaAllocation allocation, VmaAllocationInfo* pAllocationInfo)
	vmaGetAllocationInfo;

void function(VmaAllocator allocator, VmaAllocation allocation, VmaAllocationInfo2* pAllocationInfo)
	vmaGetAllocationInfo2;

void function(VmaAllocator allocator, VmaAllocation allocation, VkMemoryPropertyFlags* pFlags)
	vmaGetAllocationMemoryProperties;

void function(VmaAllocator allocator, VmaAllocatorInfo* pAllocatorInfo)
	vmaGetAllocatorInfo;

void function(VmaAllocator allocator, VmaBudget* pBudgets)
	vmaGetHeapBudgets;

void function(VmaAllocator allocator, VkPhysicalDeviceMemoryProperties** ppPhysicalDeviceMemoryProperties)
	vmaGetMemoryProperties;

void function(VmaAllocator allocator, uint32_t memoryTypeIndex, VkMemoryPropertyFlags* pFlags)
	vmaGetMemoryTypeProperties;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, HANDLE hTargetProcess, HANDLE* pHandle)
	vmaGetMemoryWin32Handle;

void function(VmaAllocator allocator, VkPhysicalDeviceProperties** ppPhysicalDeviceProperties)
	vmaGetPhysicalDeviceProperties;

void function(VmaAllocator allocator, VmaPool pool, immutable(char)** ppName)
	vmaGetPoolName;

void function(VmaAllocator allocator, VmaPool pool, VmaStatistics* pPoolStats)
	vmaGetPoolStatistics;

void function(VmaVirtualBlock virtualBlock, VmaVirtualAllocation allocation, VmaVirtualAllocationInfo* pVirtualAllocInfo)
	vmaGetVirtualAllocationInfo;

void function(VmaVirtualBlock virtualBlock, VmaStatistics* pStats)
	vmaGetVirtualBlockStatistics;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, VkDeviceSize offset, VkDeviceSize size)
	vmaInvalidateAllocation;

VkResult function(VmaAllocator allocator, uint32_t allocationCount, VmaAllocation* allocations, VkDeviceSize* offsets, VkDeviceSize* sizes)
	vmaInvalidateAllocations;

VkBool32 function(VmaVirtualBlock virtualBlock)
	vmaIsVirtualBlockEmpty;

VkResult function(VmaAllocator allocator, VmaAllocation allocation, void** ppData)
	vmaMapMemory;

void function(VmaAllocator allocator, VmaAllocation allocation, immutable(char)* pName)
	vmaSetAllocationName;

void function(VmaAllocator allocator, VmaAllocation allocation, void* pUserData)
	vmaSetAllocationUserData;

void function(VmaAllocator allocator, uint32_t frameIndex)
	vmaSetCurrentFrameIndex;

void function(VmaAllocator allocator, VmaPool pool, immutable(char)* pName)
	vmaSetPoolName;

void function(VmaVirtualBlock virtualBlock, VmaVirtualAllocation allocation, void* pUserData)
	vmaSetVirtualAllocationUserData;

void function(VmaAllocator allocator, VmaAllocation allocation)
	vmaUnmapMemory;

VkResult function(VmaVirtualBlock virtualBlock, VmaVirtualAllocationCreateInfo* pCreateInfo, VmaVirtualAllocation* pAllocation, VkDeviceSize* pOffset)
	vmaVirtualAllocate;

void function(VmaVirtualBlock virtualBlock, VmaVirtualAllocation allocation)
	vmaVirtualFree;

}} // extern(C), __gshared

