#version 450 core
#extension GL_ARB_separate_shader_objects   : enable
#extension GL_ARB_shading_language_420pack  : enable
#extension GL_GOOGLE_include_directive      : require

#define GROUP_SIZE_X 64
#define GROUP_SIZE_Y 1
layout(local_size_x = GROUP_SIZE_X, local_size_y = GROUP_SIZE_Y) in;

layout(set=0, binding=0, std430) readonly buffer I0 {
	float dataIn[];
};
layout(set=0, binding=1, std430) writeonly buffer O0 {
	float dataOut[];
};

ivec2 g_pos  = ivec2(gl_GlobalInvocationID.xy);
ivec2 l_pos  = ivec2(gl_LocalInvocationID.xy);
uint g_index = gl_GlobalInvocationID.x;
               //gl_GlobalInvocationID.y*SIZE.x;
uint l_index = gl_LocalInvocationIndex;

void main() {
    /* Write the input + 10 to the output */
    dataOut[g_index] = dataIn[g_index] + 10.0f;
}
